const createTrack = () => {
  return Math.floor(Math.random() * 28) + 1;
};
export const items = [
  { id: 1, content: "width", track: createTrack() },
  { id: 2, content: "height", track: createTrack() },
  { id: 3, content: "312", track: createTrack() },
  { id: 4, content: "width", track: createTrack() },
  { id: 5, content: "height", track: createTrack() },
  { id: 6, content: "312", track: createTrack() },
  { id: 7, content: "width", track: createTrack() },
  { id: 8, content: "height", track: createTrack() },
  { id: 9, content: "312", track: createTrack() },
  {
    id: 10,
    content:
      "width----------------width----------------width----------------width----------------",
    track: createTrack(),
  },
  { id: 11, content: "height", track: createTrack() },
  { id: 12, content: "312", track: createTrack() },
  { id: 13, content: "width", track: createTrack() },
  { id: 14, content: "height", track: createTrack() },
  { id: 15, content: "312", track: createTrack() },
  { id: 16, content: "width", track: createTrack() },
  { id: 17, content: "height", track: createTrack() },
  { id: 18, content: "312", track: createTrack() },
  { id: 19, content: "width", track: createTrack() },
  { id: 20, content: "height", track: createTrack() },
  { id: 21, content: "312", track: createTrack() },
  { id: 1, content: "width", track: createTrack() },
  { id: 2, content: "height", track: createTrack() },
  { id: 3, content: "312", track: createTrack() },
  { id: 4, content: "width", track: createTrack() },
  { id: 5, content: "height", track: createTrack() },
  { id: 6, content: "312", track: createTrack() },
  { id: 7, content: "width", track: createTrack() },
  { id: 8, content: "height", track: createTrack() },
  { id: 9, content: "312", track: createTrack() },
  {
    id: 10,
    content:
      "width----------------width----------------width----------------width----------------",
    track: createTrack(),
  },
  { id: 11, content: "height", track: createTrack() },
  { id: 12, content: "312", track: createTrack() },
  { id: 13, content: "width", track: createTrack() },
  { id: 14, content: "height", track: createTrack() },
  { id: 15, content: "312", track: createTrack() },
  { id: 16, content: "width", track: createTrack() },
  { id: 17, content: "height", track: createTrack() },
  { id: 18, content: "312", track: createTrack() },
  { id: 19, content: "width", track: createTrack() },
  { id: 20, content: "height", track: createTrack() },
  { id: 21, content: "312", track: createTrack() },
];
